# -*- coding: utf-8 -*-
"""Análisis de Datos FAC - Bienestar Familiar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pBDJJeWRsua4-iPxqszbNrs_tH_lNb0Q
"""

# analisis_familiar.py
import pandas as pd #Pandas sirve para leer, limpiar y analizar datos en tablas (DataFrames)
import matplotlib.pyplot as plt # Se usa para hacer gráficas
# Leer los datos
df = pd.read_excel("/content/JEFAB_2024_corregido.xlsx")

# Análisis de estado civil
print("=== ANÁLISIS ESTADO CIVIL ===")
print(df['ESTADO_CIVIL'].value_counts()) # cuenta cuántas veces aparece cada categoría en esa columna.

# Porcentaje para estado civil
porcentajes = df['ESTADO_CIVIL'].value_counts(normalize=True) * 100
print(porcentajes)

# Análisis de hijos
print("\n=== ANÁLISIS DE HIJOS ===")
print(f"Personal con hijos: {df['HIJOS'].value_counts()}")

# Análisis de convivencia familiar
print("\n=== ANÁLISIS DE CONVIVENCIA ===")
print(f"Habita con familia: {df['HABITA_VIVIENDA_FAMILIAR'].value_counts()}")

# Cruce entre tener hijos y habitar con familia
print("\n=== CRUCE HIJOS Y CONVIVENCIA ===")
cruce = pd.crosstab(df['HIJOS'], df['HABITA_VIVIENDA_FAMILIAR'])
print(cruce)

print(df.groupby("ESTADO_CIVIL")["EDAD2"].mean())

df.groupby("ESTADO_CIVIL")["EDAD2"].mean().plot(kind="bar")
plt.show()

plt.figure(figsize=(10,6))
df.boxplot(column="EDAD2", by="ESTADO_CIVIL", grid=False)
plt.title("Distribución de la edad según Estado Civil")
plt.suptitle("")  # elimina título extra de pandas
plt.xlabel("Estado Civil")
plt.ylabel("Edad")
plt.xticks(rotation=45)
plt.show()

# Gráfico de estado civil
plt.figure(figsize=(10, 6)) # define el tamaño en pulgadas (ancho=10, alto=6).
df['ESTADO_CIVIL'].value_counts().plot(kind='bar') # selecciona la columna de estado civil,cuenta cuántas veces aparece cada categoría.
plt.title('Distribución del Estado Civil')
plt.xlabel('Estado Civil')
plt.ylabel('Cantidad')
plt.xticks(rotation=45) # Rota las etiquetas del eje X 45 grados.
plt.tight_layout() # Ajusta automáticamente márgenes y espaciado.
plt.show() # Muestra el grafico